# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-15 08:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleBase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='articles')),
                ('purchasing_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Purchasing price')),
                ('selling_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Selling price')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Name')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('quantity', models.IntegerField(default=1, verbose_name='Quantity')),
            ],
            options={
                'verbose_name': 'Article with minimal data',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Category')),
            ],
        ),
        migrations.AlterField(
            model_name='article',
            name='arrivage',
            field=models.ForeignKey(blank=True, default=3, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.Arrivage', verbose_name='Arrivage'),
        ),
        migrations.AlterField(
            model_name='article',
            name='genre_article',
            field=models.CharField(choices=[('A', 'Accessoire'), ('V', 'Vêtement'), ('C', 'Chaussure'), ('S', 'Sous-vêtement')], default='S', max_length=1, verbose_name="Genre d'article"),
        ),
        migrations.AlterField(
            model_name='article',
            name='nom',
            field=models.CharField(default='ensemble', max_length=100, verbose_name='Nom'),
        ),
        migrations.AlterField(
            model_name='article',
            name='solde',
            field=models.CharField(choices=[('N', '-'), ('S', 'en solde')], default='N', max_length=1, verbose_name='en solde'),
        ),
        migrations.AlterField(
            model_name='article',
            name='type_client',
            field=models.CharField(choices=[('H', 'Homme'), ('F', 'Femme'), ('M', 'Mixte'), ('E', 'Enfant')], default='F', max_length=1, verbose_name='Type de client'),
        ),
        migrations.CreateModel(
            name='ClothesArticle',
            fields=[
                ('articlebase_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='inventory.ArticleBase')),
                ('type_client', models.CharField(choices=[('H', 'Homme'), ('F', 'Femme'), ('M', 'Mixte'), ('E', 'Enfant')], default='F', max_length=1, verbose_name='Type de client')),
                ('marque', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.Marque')),
            ],
            bases=('inventory.articlebase',),
        ),
        migrations.AddField(
            model_name='articlebase',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.Category', verbose_name='Category'),
        ),
    ]
