# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-15 09:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_auto_20180215_0215'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleClothes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo_no', models.PositiveSmallIntegerField(blank=True, help_text='no de la prise de vue', null=True, unique=True)),
                ('type_client', models.CharField(choices=[('H', 'Homme'), ('F', 'Femme'), ('M', 'Mixte'), ('E', 'Enfant')], default='F', max_length=1, verbose_name='Type de client')),
                ('genre_article', models.CharField(choices=[('A', 'Accessoire'), ('V', 'Vêtement'), ('C', 'Chaussure'), ('S', 'Sous-vêtement')], default='S', max_length=1, verbose_name="Genre d'article")),
                ('nom', models.CharField(default='ensemble', max_length=100, verbose_name='Nom')),
                ('quantite', models.IntegerField(default=1)),
                ('prix_unitaire', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('prix_total', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('remise', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True)),
                ('date_ajout', models.DateField(auto_now_add=True)),
                ('couleurs_quantites', models.CharField(blank=True, max_length=200, null=True)),
                ('motifs', models.CharField(blank=True, max_length=200, null=True)),
                ('notes', models.CharField(blank=True, max_length=200, null=True)),
                ('type_taille', models.CharField(blank=True, choices=[('1', 'EUR'), ('2', 'US'), ('3', 'UK')], default='1', max_length=1, null=True)),
                ('taille', models.CharField(blank=True, choices=[('1', 'S'), ('2', 'M'), ('3', 'L'), ('4', 'XL'), ('5', 'XXL'), ('6', 'XXXL'), ('7', 'XXXXL'), ('8', '5XL'), ('9', '6XL'), ('10', '7XL'), ('11', '8XL')], max_length=2, null=True)),
                ('taille_nombre', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('local', models.CharField(default='bas', max_length=20)),
                ('solde', models.CharField(choices=[('N', '-'), ('S', 'en solde')], default='N', max_length=1, verbose_name='en solde')),
                ('ventes', models.CharField(blank=True, help_text='25000, 35000', max_length=200, null=True)),
                ('tailles_vendues', models.CharField(blank=True, help_text='(XL, 1), (M, 2)', max_length=200, null=True)),
                ('arrivage', models.ForeignKey(blank=True, default=3, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.Arrivage', verbose_name='Arrivage')),
                ('entreprise', models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='inventory.Enterprise')),
                ('marque', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.Marque')),
            ],
            options={
                'ordering': ['pk'],
            },
        ),
        migrations.RemoveField(
            model_name='articlebase',
            name='category',
        ),
        migrations.RemoveField(
            model_name='clothesarticle',
            name='articlebase_ptr',
        ),
        migrations.RemoveField(
            model_name='clothesarticle',
            name='marque',
        ),
        migrations.RemoveField(
            model_name='photo',
            name='article',
        ),
        migrations.AlterModelOptions(
            name='article',
            options={'verbose_name': 'Article with minimal data'},
        ),
        migrations.RemoveField(
            model_name='article',
            name='arrivage',
        ),
        migrations.RemoveField(
            model_name='article',
            name='couleurs_quantites',
        ),
        migrations.RemoveField(
            model_name='article',
            name='date_ajout',
        ),
        migrations.RemoveField(
            model_name='article',
            name='entreprise',
        ),
        migrations.RemoveField(
            model_name='article',
            name='genre_article',
        ),
        migrations.RemoveField(
            model_name='article',
            name='local',
        ),
        migrations.RemoveField(
            model_name='article',
            name='marque',
        ),
        migrations.RemoveField(
            model_name='article',
            name='motifs',
        ),
        migrations.RemoveField(
            model_name='article',
            name='nom',
        ),
        migrations.RemoveField(
            model_name='article',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='article',
            name='photo_no',
        ),
        migrations.RemoveField(
            model_name='article',
            name='prix_total',
        ),
        migrations.RemoveField(
            model_name='article',
            name='prix_unitaire',
        ),
        migrations.RemoveField(
            model_name='article',
            name='quantite',
        ),
        migrations.RemoveField(
            model_name='article',
            name='remise',
        ),
        migrations.RemoveField(
            model_name='article',
            name='solde',
        ),
        migrations.RemoveField(
            model_name='article',
            name='taille',
        ),
        migrations.RemoveField(
            model_name='article',
            name='taille_nombre',
        ),
        migrations.RemoveField(
            model_name='article',
            name='tailles_vendues',
        ),
        migrations.RemoveField(
            model_name='article',
            name='type_client',
        ),
        migrations.RemoveField(
            model_name='article',
            name='type_taille',
        ),
        migrations.RemoveField(
            model_name='article',
            name='ventes',
        ),
        migrations.AddField(
            model_name='article',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.Category', verbose_name='Category'),
        ),
        migrations.AddField(
            model_name='article',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='article',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='article',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='articles'),
        ),
        migrations.AddField(
            model_name='article',
            name='purchasing_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Purchasing price'),
        ),
        migrations.AddField(
            model_name='article',
            name='quantity',
            field=models.IntegerField(default=1, verbose_name='Quantity'),
        ),
        migrations.AddField(
            model_name='article',
            name='selling_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Selling price'),
        ),
        migrations.DeleteModel(
            name='ArticleBase',
        ),
        migrations.DeleteModel(
            name='ClothesArticle',
        ),
        migrations.DeleteModel(
            name='Photo',
        ),
    ]
