# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-15 10:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_auto_20180215_0347'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='solde',
            field=models.CharField(choices=[('N', '-'), ('S', 'en solde')], default='N', max_length=1, verbose_name='en solde'),
        ),
    ]
