# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-15 10:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_article_solde'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='enterprise',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='inventory.Enterprise'),
        ),
    ]
