# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-16 13:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_article_enterprise'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['pk'], 'verbose_name': 'Article with minimal data'},
        ),
        migrations.RemoveField(
            model_name='arrivage',
            name='proprietaire',
        ),
        migrations.RemoveField(
            model_name='article',
            name='enterprise',
        ),
        migrations.AddField(
            model_name='article',
            name='arrival',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='inventory.Arrivage'),
        ),
        migrations.AddField(
            model_name='article',
            name='notes',
            field=models.TextField(blank=True, default='n.d.', null=True, verbose_name='Notes'),
        ),
        migrations.AlterField(
            model_name='arrivage',
            name='date_arrivee',
            field=models.DateField(verbose_name='Arrival Date'),
        ),
        migrations.AlterField(
            model_name='article',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.Category', verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='article',
            name='description',
            field=models.TextField(blank=True, default='n.d.', null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='article',
            name='name',
            field=models.CharField(blank=True, default='n.d.', max_length=100, null=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='article',
            name='photo',
            field=models.ImageField(blank=True, null=True, unique=True, upload_to='articles'),
        ),
        migrations.AlterField(
            model_name='article',
            name='purchasing_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Purchasing price'),
        ),
        migrations.AlterField(
            model_name='article',
            name='selling_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Selling price'),
        ),
    ]
