# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-23 09:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_auto_20180216_0745'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='arrival',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.Arrivage'),
        ),
    ]
