# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-26 13:33
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cart_id', models.CharField(max_length=50)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('quantity', models.IntegerField(default=1)),
                ('prix', models.DecimalField(decimal_places=0, default=25000, max_digits=20)),
                ('cart_complete', models.BooleanField(default=False)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.Article')),
            ],
            options={
                'db_table': 'cart_items',
                'ordering': ['date_added'],
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=80)),
                ('prenom', models.CharField(max_length=80)),
                ('tel', models.CharField(help_text="pas d'espaces entre les chiffres svp", max_length=20, validators=[django.core.validators.RegexValidator(message="Format: '+999999999'. Maximum 20 chiffres.", regex='^\\+?1?\\d{9,20}$')])),
            ],
        ),
        migrations.CreateModel(
            name='Paiement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('montant', models.DecimalField(decimal_places=0, default=0, max_digits=20)),
            ],
        ),
        migrations.CreateModel(
            name='Vente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('montant', models.DecimalField(decimal_places=0, default=0, max_digits=20)),
                ('reglement_termine', models.BooleanField(default=False)),
                ('client', models.ForeignKey(blank=True, help_text="Laisser le champ vide (---) si le client n'est pas enregistré.", null=True, on_delete=django.db.models.deletion.CASCADE, to='cart.Client')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.AddField(
            model_name='paiement',
            name='vente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cart.Vente'),
        ),
        migrations.AlterUniqueTogether(
            name='client',
            unique_together=set([('nom', 'prenom')]),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='vente',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cart.Vente'),
        ),
    ]
