# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-02 16:27
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='tel',
            field=models.CharField(blank=True, help_text="pas d'espaces entre les chiffres svp", max_length=20, null=True, validators=[django.core.validators.RegexValidator(message="Format: '+999999999'. Maximum 20 chiffres.", regex='^\\+?1?\\d{9,20}$')]),
        ),
    ]
