# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-15 08:15
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_auto_20180202_1727'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='cart_complete',
            field=models.BooleanField(default=False, verbose_name='Panier validé'),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='prix',
            field=models.DecimalField(decimal_places=0, default=25000, max_digits=20, verbose_name='Prix'),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='vente',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cart.Vente', verbose_name='Vente'),
        ),
        migrations.AlterField(
            model_name='client',
            name='nom',
            field=models.CharField(max_length=80, verbose_name='Nom'),
        ),
        migrations.AlterField(
            model_name='client',
            name='prenom',
            field=models.CharField(max_length=80, verbose_name='Prénom'),
        ),
        migrations.AlterField(
            model_name='client',
            name='tel',
            field=models.CharField(blank=True, help_text="pas d'espaces entre les chiffres svp", max_length=20, null=True, validators=[django.core.validators.RegexValidator(message="Format: '+999999999'. Maximum 20 chiffres.", regex='^\\+?1?\\d{9,20}$')], verbose_name='Tél.'),
        ),
        migrations.AlterField(
            model_name='paiement',
            name='montant',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=20, verbose_name='Montant'),
        ),
        migrations.AlterField(
            model_name='paiement',
            name='vente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cart.Vente', verbose_name='Vente'),
        ),
        migrations.AlterField(
            model_name='vente',
            name='client',
            field=models.ForeignKey(blank=True, help_text="Laisser le champ vide (---) si le client n'est pas enregistré.", null=True, on_delete=django.db.models.deletion.CASCADE, to='cart.Client', verbose_name='Client'),
        ),
        migrations.AlterField(
            model_name='vente',
            name='montant',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=20, verbose_name='montant'),
        ),
        migrations.AlterField(
            model_name='vente',
            name='reglement_termine',
            field=models.BooleanField(default=False, verbose_name='Règlement terminé'),
        ),
    ]
